# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-customer-receiver-messages:
    build:
      target: development
    image: fcp-fd-customer-receiver-messages-development
    container_name: fcp-fd-customer-receiver-messages-development
    ports:
      - "3012:3012"
      - "9012:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
